[package]
authors = ["周睿 <zrufo747@outlook.com>"]
categories = ["embedded", "no-std"]
description = "Driver Interface of interrupt controller."
edition.workspace = true
keywords = ["os", "driver"]
license = "MIT"
name = "rdif-pcie"
repository.workspace = true
version = "0.1.4"

[dependencies]
pci_types = "0.10"
rdif-base = { workspace = true }
thiserror = {version = "2", default-features = false}
