[package]
name = "enumerate"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
rdrive = { workspace = true }
rdrive-macros = { workspace = true }
env_logger = "0.11"
log ="0.4"